server:
  port: 3000
spring:
  application:
    name: crowd-redis  redis:    host: 192.168.100.130
    port: 6379
    password: rediseureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
